### ISSUE TITLE
problems with forms in cells

### ISSUE THREAD

**Issue by barriehadfield** [apotonick/trailblazer#72]
Hi - loving the book and the Trailblazer approach. I am unfortunately stuck and have spent the whole weekend on this and can't go further.

My goal is to refactor my app and get all my forms into cells. This is important to me as I will then have them render into modals and I get to clean up all the hundreds of partials I have in the views.

My problem is that I cannot get a form to work in a cell. All the examples I find keep the form in the view which Rails renders. Doing this works, but its not the deign I want. Forms need to be in cells for me.

For a simple example, here is the controller: 

```ruby
def edit
    form Company::Update
    render action: :edit
  end
```
/views/companies/edit.haml 
```haml
= concept("company/cells", @form).(:edit)
```
/concepts/company/cell.rb
```ruby
 class Company::Cell < Cell::Concept
    include SimpleForm::ActionViewExtensions::FormHelper
    include Cell::Haml

    def dom_class(record, prefix = nil)
      ActionView::RecordIdentifier.dom_class(record, prefix)
    end

    def dom_id(record, prefix = nil)
      ActionView::RecordIdentifier.dom_id(record, prefix)
    end

  property :name

  def edit
    render
  end
end
```
and finally /concepts/company/views/edit.haml
```haml
= simple_form_for model do |f|
  = f.input :name
  = f.button :submit, class: :expand
```
and now the *problem* - the resulting HTML:
```html
<div class="form-group string required company_name"><label class="string required control-label" for="company_name"><abbr title="required">*</abbr> Name</label><input class="string required form-control" type="text" value="Test company" name="company[name]" id="company_name" /></div>
  <input type="submit" name="commit" value="Update Company" class="btn btn-default expand" />
<form novalidate="novalidate" class="simple_form edit_company" id="edit_company_1" action="/companies/1" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="_method" value="patch" /><input type="hidden" name="authenticity_token" value="OvW+tMjUaOYkIDlcZzuA+2734JH4+j1uduqkIvGJlAz6xRRfxYQJRVfoodN4ySfu9w1ivCEKSjMx2liw6fLFBA==" />0</form>
```
The problem is that the SUBMIT button does not actually work, I think this is because in the HTML above the Submit button is outside the form tag, but I could be wrong as this might not be the issue.

Can anyone help me please?

**Comment by apotonick** [comment]
You need to point your haml version to a specific commit, as done here: https://github.com/apotonick/gemgem-trbrb/blob/chapter-10/Gemfile#L47

I am really sorry for this inconvenience, I've wasted about 2 weeks of my precious life with this shit, and it is fixed in Haml 5. :wink: 

Also, good news for you!!!!!!!!!!! Chapter 10 is doing forms in cells: https://github.com/apotonick/gemgem-trbrb/blob/chapter-10/app/concepts/thing/cell/form.rb :fireworks: :sunny: :sparkles: 

Thanks for your feedback, good to hear you like it.

**Comment by barriehadfield** [comment]
Thank you so much - that worked perfectly!

**Comment by pmackay** [comment]
I'm trying to resolve a similar issue. Having updated my Gemfile, I'm still getting a small chunk of hash output underneath the form, e,g `{:first_name=>[], :surname=>[]}`. Before it was rendering the HTML of the form. The form just has those two fields currently.

Any clues?

**Comment by apotonick** [comment]
@pmackay Are you printing out `form.errors` anywhere in your template? I did that in Gemgem for educational purposes.

**Comment by pmackay** [comment]
@apotonick yes that was it. I think I had it in my head that that would only cause an output if there was an issue. Thanks for the tip, much appreciated!
